#
# Module manifest for module 'connectToGraphApi'
#
# Generated by: Gabor Lakatos - glakatos@asapcloud.com
#
# Generated on: 01/02/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\connectToGraphApi.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'ffc2c93a-93d1-444d-b848-bdda62da9833'

# Author of this module
Author = 'Gabor Lakatos - glakatos@asapcloud.com'

# Company or vendor of this module
CompanyName = 'ASAPCloud'

# Copyright statement for this module
Copyright = '(c) Gabor Lakatos - glakatos@asapcloud.com. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This function will provide Access without a user to Azure AD Graph API, using a Service Principal(Application) with certificate, and return the Graph context'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Az.Accounts', 
               'Microsoft.Graph.Authentication')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'The connectToGraphApi.psd1 PowerShell module is designed to establish a connection to the Microsoft Graph API.

This module contains the Connect-MgGraph cmdlet, which is part of the Microsoft Graph PowerShell SDK. This cmdlet is used to authenticate and create a connection to the Microsoft Graph API, which allows for further interaction with Microsoft 365 services.

The Connect-MgGraph cmdlet supports different authentication methods including interactive login, device code, client credentials, username/password, and certificate.

This module exports the Connect-MgGraph cmdlet, making it available for use in other scripts or modules. The cmdlet is essential for any PowerShell script or module that needs to interact with Microsoft 365 services via the Microsoft Graph API.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

